#!/bin/env bash

if [[ $# -eq 0 || $1 == '-h' || $1 == '--help' ]]; then
    echo "Usage: mpvline [-option] [MusicPath]"
    echo "using mpv easily in Command lines"
    echo "-c, --close       close mpvline"
    echo "-L, --latest      play latest 30 music of ~/Music"
    echo
    echo "play "~/Music" by default"
fi

if [[ $(pgrep mpv) && ("$1" = '-c' || "$1" = '--close') ]]; then
    kill -KILL $(pgrep mpv)
    exit 0
fi

if [[ "$1" = '-L' || "$1" = '--latest' ]]; then
    find ${HOME}/Music -type f -iname "*.mp3" -printf '%T@ %p\0' | \
        sort -znr | head -zn30 | cut -zd' ' -f2- | \
        xargs -0 mpv --shuffle --no-audio-display --vo=null
fi

if [[ -z $1 ]]; then # if the length of $1 is zero; then
    # play ~/Music by default
    mpv --shuffle -no-audio-display --vo=null "/home/hk416/Music"
    exit 0 
fi

# path=$1
# 
# # add the trans of ~
# # emmm.. it seems that there's no need to trans, because mpv can resolve it
# if [[ ${path%%/*} = "~" ]]; then
#     path="${HOME}/${path#*/}"     
# fi 

if [[ ! (-d "$1" || -f "$1") ]]; then # if $1 is not a dir or file
    echo "plz enter the correct Path"
    exit 2
fi

mpv --shuffle --no-audio-display --vo=null "$1"
# --no-terminal

exit 0
