#!/bin/env bash

if [[ $# -eq 0 || $1 == '-h' || $1 == '--help' ]]; then
    echo "Usage: sound [OPTION]..."
    echo "Change the sound of your computer"
    echo 
    echo "  -s, --set=INT   set sound volumn by 100%"
    echo "  -m, --mute      mute the speaker"
    echo "  --unmute        unmute the speaker"
    echo "  -h, --help      show help"
#    echo "  -c, --current   show current sound value"
    echo 
    echo "only when realy changed sound, then return 0" 
    exit 1
fi

if [[ $1 == '--mute' || $1 == '-m' ]]; then
    amixer -D pulse sset Master mute
fi

if [[ $1 == '--unmute' ]]; then
    amixer -D pulse sset Master unmute
fi

if [[ -z $2 ]]; then # if the length of $2 is zero; then
    echo "plz enter the value(0 - 100)"
    exit 2
fi

if [[ $1 == '-s' || $1 == '--set' ]]; then
    amixer -D pulse sset Master "${2}%"
fi 

exit 0
