#!/bin/env bash


MAX_BRIGHTNESS=`cat /sys/class/backlight/amdgpu_bl0/max_brightness`
BRIGHTNESS_PATH='/sys/class/backlight/amdgpu_bl0/brightness'

if [ $# -eq 0 ]; then
    echo "try -h or --help plz"
    exit 1
fi

# case might be better? 
if [[ $1 == '-h' || $1 == '--help' ]]; then
    echo "Usage: brightness [OPTION]..."
    echo "Change the brightness of your computer"
    echo ""
    echo "  -s, --set=INT   set brightness at INT"
    echo "  -m, --max       get the max brightness value"
    echo "  -h, --help      show help"
    echo "  -c, --current   show current brightness value"
    echo ""
    echo "only when realy changed brightness, then return 0" 
    exit 1
fi

if [[ $1 == '-m' || $1 == '--max' ]]; then
    echo "the max brightness value is: $MAX_BRIGHTNESS"
    exit 1
fi

if [[ $1 == '-c' || $1 == '--current' ]]; then
    echo -n "the current brightness value is: "
    cat $BRIGHTNESS_PATH
    exit 1
fi

if [[ -n $2 && ($1 == '-s' || $1 == '--set') ]]; then
    BRIGHTNESS=$(( $2>MAX_BRIGHTNESS?MAX_BRIGHTNESS:$2 ))
    echo $BRIGHTNESS | sudo tee /sys/class/backlight/amdgpu_bl0/brightness
    echo set over~
fi 

exit 0
