-- generated by hk416hasu
library IEEE;
use ieee.std_logic_unsigned.all;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity cpu is
	Port ( 
		CLK       : in STD_LOGIC; -- 单步时钟信号, 控制取指
		CLK0      : in STD_LOGIC; -- 50MHZ时钟信号, 自动执行
		RST       : in STD_LOGIC; -- 复位信号
		INPUT     : in STD_LOGIC_VECTOR (15 downto 0); -- 拨码开关输入指令
		LED       : out STD_LOGIC_VECTOR(15 downto 0); -- LED输出
		stateCnt1 : out STD_LOGIC_VECTOR(6  downto 0); -- 7段数码管
		stateCnt2 : out STD_LOGIC_VECTOR(6  downto 0); -- 7段数码管
		M_EN      : out STD_LOGIC; -- Memory_Enable
		M_OE      : out STD_LOGIC; -- Memory_Output_Enable
		M_WE      : out STD_LOGIC; -- Memory_Write_Enable
		Addr      : out   STD_LOGIC_VECTOR(17 downto 0); -- 地址信号, 18位, 与外总线连接
		Data      : inout STD_LOGIC_VECTOR(15 downto 0)  -- Data信号, 16位, 与外总线连接
	);
end entity cpu;

architecture bhv of cpu is
	signal r0, r1, r2, r3, r4, r5, r6, r7 : STD_LOGIC_VECTOR(15 downto 0); -- 通用寄存器组
	signal acc : STD_LOGIC_VECTOR(15 downto 0); -- 累加寄存器
	signal b : STD_LOGIC_VECTOR(15 downto 0);
	signal pc : STD_LOGIC_VECTOR(15 downto 0); -- 程序计数器
	signal ir : STD_LOGIC_VECTOR(15 downto 0); -- 指令寄存器
	signal MAR : STD_LOGIC_VECTOR(17 downto 0);
	signal MBR : STD_LOGIC_VECTOR(15 downto 0);
	signal SR : STD_LOGIC_VECTOR(15 downto 0); -- 移位寄存器
	
	signal rx, ry, rz : STD_LOGIC_VECTOR(2 downto 0); -- 目的寄存器
	
	signal T0 : STD_LOGIC;
	signal T1 : STD_LOGIC;
	signal T2 : STD_LOGIC;
	signal T3 : STD_LOGIC;
	
	signal Ex : STD_LOGIC; -- Execute
	signal Fe : STD_LOGIC; -- Fetch
	
	signal SendPCtoAcc : STD_LOGIC;
	signal Pass_ALU : STD_LOGIC;
	signal DM_SR : STD_LOGIC;
	signal CPMAR : STD_LOGIC;
	signal EMAR : STD_LOGIC;
	signal SIR : STD_LOGIC;
	signal Add_ALU : STD_LOGIC;
	signal CPPC : STD_LOGIC;
	signal SendIRtoAcc : STD_LOGIC;
	signal SLL11_ALU : STD_LOGIC;
	signal SRA11_SR : STD_LOGIC;
	signal CPACC : STD_LOGIC;
	signal SendRiToB : STD_LOGIC;
	signal SMBR : STD_LOGIC;
	signal SendRiToACC : STD_LOGIC;
	signal SLL8_ALU : STD_LOGIC;
	signal SRA8_SR : STD_LOGIC;
	signal SLL5_ALU : STD_LOGIC;
	signal SRA5_SR : STD_LOGIC;
	signal SRL8_SR : STD_LOGIC;
	signal CPRi : STD_LOGIC;
	signal BeqzPC : STD_LOGIC;
	signal SendPCtoB : STD_LOGIC;
	signal CPPSW : STD_LOGIC;
	signal SendMBRtoACC : STD_LOGIC;
	